{
 "title": "Azure Pipelines",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Azure Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(last_over_time(azure_devops_build_status{name!='', result=\"succeeded\"}[$__range])) / count(last_over_time(azure_devops_build_status{name!=''}[$__range])))*100"
    }
   ]
  },
  {
   "title": "Count Pipelines ( by result )",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(azure_devops_build_latency{name!=''}[$__range])) by(result)"
    }
   ]
  },
  {
   "title": "Count pipeline (by name )",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(azure_devops_build_latency{name!=''}[$__range])) by(name)"
    }
   ]
  },
  {
   "title": "Pipeline latency ( in seconds )",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(azure_devops_build_latency{name!=\"\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count pipelines ( by user )",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(count(last_over_time(azure_devops_build_status{triggeredBy!=''}[$__range])) by (triggeredBy))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline list",
   "type": "table",
   "gridPos": { "h": 15, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time(azure_devops_build_status{name!=\"\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}